#!/bin/bash


# MANUAL
DEFAULT=$(ip r | grep default | awk '{print $5}')

NET=epfiot-net
ADDR=10.0.0.1/24

if [[ -n `ip a | grep $NET` ]]; then
    ip link delete $NET type bridge
fi

ip link add name $NET type bridge
ip link set $NET up

ip addr add dev $NET $ADDR

iptables -t nat -A POSTROUTING -o $DEFAULT -j MASQUERADE

# LIBVIRT MANAGED
#virsh net-define --file xml/default.xml
#virsh net-start default
#virsh net-autostart --network default


