#!/bin/bash

if [ "$EUID" -ne 0 ]
    then echo "Please run as root"
    exit
fi

NET=epfiot_net

if [[ -n `ip a | grep $NET` ]]; then
    ip link delete $NET type bridge
fi

ip link add name $NET type bridge
ip link set $NET up
ip link set wlp2s0 master $NET
ip addr add dev $NET 10.0.0.1/8
